version: "2.1"
services:

  coordinator:
    networks: ["vnet"]
    image: smizy/presto:0.185-alpine
    ports:
      - 8080:8080
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm
      - PRESTO_DISCOVERY_URI=http://coordinator:8080
#    depends_on: ["php"]
    volumes:
      - ./catalog:/usr/local/presto-server-0.185/etc/catalog
    command: coordinator

  worker:
    networks: ["vnet"]
    image: smizy/presto:0.185-alpine
    depends_on: ["coordinator"]
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm
      - PRESTO_DISCOVERY_URI=http://coordinator:8080
    links:
      - php
    volumes:
      - ./catalog:/usr/local/presto-server-0.185/etc/catalog
    command: worker

  thrift:
    image: thrift
    working_dir: /code
    volumes:
      - ./:/code/

  composer:
    image: composer
    working_dir: /code
    volumes:
      - ./:/code/

  php:
    image: php:fpm
    tty: true
    networks: ["vnet"]
    working_dir: /code/src
    volumes:
      - .:/code/

  web:
    image: nginx
    networks: ["vnet"]
    ports:
      - "8000:80"
    volumes:
      - ./:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  vnet:
    external:
      name: vnet